# BoW 기반 텍스트 분석 연습

1. 적절한 데이터셋을 찾거나 생성하고, 적절한 전처리를 진행한다. [01_preprocessing.ipynb]
2. TF-IDF Vectorizer를 이용하여 벡터화한다.
3. Cosine Similarity를 계산하여 입력된 문자열의 긍/부정을 판단한다.

In [23]:
import pandas as pd
import numpy as np

In [17]:
text_df = pd.read_csv('./preprocessing_data.csv', encoding='utf-8')
text_df

,label,document,tokens
0,0,노래가 너무 적음,"['노래', '너무', '적다']"
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"['돌다', '진짜', '황숙', '어크', '공장', '그만', '돌리다', '죽다']"
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"['막노동', '체험판', '막노동', '사람', '인데', '장비', '사다', ..."
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"['차악차악', '정말', '이래서', '왕국', '되찾다']"
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"['때우다', '좋다', '도전', '과제', '이면', '깨다']"
...,...,...,...
99995,0,한글화해주면 개산다,"['한글화', '해주다', '산다']"
99996,0,개쌉노잼,"['싸다', '노잼']"
99997,0,노잼이네요 분하고 지웠어요,"['노잼', '이네', '분하다', '지우다']"
99998,1,야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기 영어는 그리 어렵지 않습니다,"['야생', '사랑', '사람', '짧다', '여운', '남다', '이야기', '영..."
99999,1,한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임,"['한국', '메탈레이지', '떠오르다', '진짜', '손맛', '게임']"

In [ ]:
import ast

text_df['tokens'] = text_df['tokens'].apply(ast.literal_eval)
text_df['string'] = text_df['tokens'].apply(lambda x: ' '.join(x))

text_df

,label,document,tokens,string
0,0,노래가 너무 적음,"[노래, 너무, 적다]",노래 너무 적다
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"[돌다, 진짜, 황숙, 어크, 공장, 그만, 돌리다, 죽다]",돌다 진짜 황숙 어크 공장 그만 돌리다 죽다
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"[막노동, 체험판, 막노동, 사람, 인데, 장비, 사다, 돼다]",막노동 체험판 막노동 사람 인데 장비 사다 돼다
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"[차악차악, 정말, 이래서, 왕국, 되찾다]",차악차악 정말 이래서 왕국 되찾다
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"[때우다, 좋다, 도전, 과제, 이면, 깨다]",때우다 좋다 도전 과제 이면 깨다
...,...,...,...,...
99995,0,한글화해주면 개산다,"[한글화, 해주다, 산다]",한글화 해주다 산다
99996,0,개쌉노잼,"[싸다, 노잼]",싸다 노잼
99997,0,노잼이네요 분하고 지웠어요,"[노잼, 이네, 분하다, 지우다]",노잼 이네 분하다 지우다
99998,1,야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기 영어는 그리 어렵지 않습니다,"[야생, 사랑, 사람, 짧다, 여운, 남다, 이야기, 영어, 그리다, 어렵다]",야생 사랑 사람 짧다 여운 남다 이야기 영어 그리다 어렵다
99999,1,한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임,"[한국, 메탈레이지, 떠오르다, 진짜, 손맛, 게임]",한국 메탈레이지 떠오르다 진짜 손맛 게임

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
text_vecs = tfidf_vectorizer.fit_transform(text_df['string'])

print(text_vecs)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 839969 stored elements and shape (100000, 32360)>
  Coords	Values
  (0, 4659)	0.6952685569344988
  (0, 4449)	0.3785753782098648
  (0, 23345)	0.610968343493734
  (1, 6388)	0.3439261294981849
  (1, 25276)	0.20389821554018478
  (1, 31851)	0.5046063403074367
  (1, 18589)	0.3645979576051492
  (1, 2053)	0.42830755714457464
  (1, 2879)	0.34598332638598256
  (1, 6398)	0.29176075517101424
  (1, 24657)	0.2535841909058848
  (2, 8796)	0.8226947579746686
  (2, 26248)	0.33668718873578174
  (2, 13682)	0.15925531357304087
  (2, 22015)	0.18178944792001284
  (2, 22926)	0.29304281239764307
  (2, 13666)	0.15576337303972737
  (2, 6545)	0.20314796476276473
  (3, 25775)	0.5698775913896675
  (3, 23726)	0.21604148260553568
  (3, 21643)	0.41008789868771023
  (3, 20106)	0.4760577562009386
  (3, 6579)	0.4834899551555743
  (4, 7200)	0.5122866071330121
  (4, 24443)	0.24619652724169475
  :	:
  (99995, 30982)	0.45035033302542643
  (99995, 30615)	0.5109933852605298
  (99995, 13919)	0.7321682441651448
  (99996, 4724)	0.6700340821364424
  (99996, 16795)	0.7423303366935606
  (99997, 4724)	0.41607009457801936
  (99997, 21571)	0.4600317179097687
  (99997, 25098)	0.5073711192868327
  (99997, 12580)	0.5981898045173049
  (99998, 13682)	0.19774761714466815
  (99998, 18338)	0.21759593900039387
  (99998, 13686)	0.34467629452234827
  (99998, 4255)	0.30434465655574533
  (99998, 25469)	0.25629303917560964
  (99998, 2859)	0.3157108882525995
  (99998, 19518)	0.2704954534018891
  (99998, 21797)	0.311411409345766
  (99998, 19257)	0.3812293301942959
  (99998, 18093)	0.47040442599016213
  (99999, 25276)	0.24723641507310168
  (99999, 1369)	0.11654435102949069
  (99999, 30603)	0.34002362317689155
  (99999, 15136)	0.45488756914442885
  (99999, 7249)	0.46141159208845767
  (99999, 9493)	0.6243814115673545

In [24]:
ko_stopwords = set("아 휴 아이구 아이쿠 아이고 어 나 우리 저희 따라 의해 을 를 에 의 가 으로 로 에게 뿐이다 의거하여 근거하여 입각하여 기준으로 예하면 예를 들면 예를 들자면 저 소인 소생 저희 지말고 하지마 하지마라 다른 물론 또한 그리고 비길수 없다 해서는 안된다 뿐만 아니라 만이 아니다 만은 아니다 막론하고 관계없이 그치지 않다 그러나 그런데 하지만 든간에 논하지 않다 따지지 않다 설사 비록 더라도 아니면 만 못하다 하는 편이 낫다 불문하고 향하여 향해서 향하다 쪽으로 틈타 이용하여 타다 오르다 제외하고 이 외에 이 밖에 하여야 비로소 한다면 몰라도 외에도 이곳 여기 부터 기점으로 따라서 할 생각이다 하려고하다 이리하여 그리하여 그렇게 함으로써 하지만 일때 할때 앞에서 중에서 보는데서 으로써 로써 까지 해야한다 일것이다 반드시 할줄알다 할수있다 할수있어 임에 틀림없다 한다면 등 등등 제 겨우 단지 다만 할뿐 딩동 댕그 대해서 대하여 대하면 훨씬 얼마나 얼마만큼 얼마큼 남짓 여 얼마간 약간 다소 좀 조금 다수 몇 얼마 지만 하물며 또한 그러나 그렇지만 하지만 이외에도 대해 말하자면 뿐이다 다음에 반대로 반대로 말하자면 이와 반대로 바꾸어서 말하면 바꾸어서 한다면 만약 그렇지않으면 까악 툭 딱 삐걱거리다 보드득 비걱거리다 꽈당 응당 해야한다 에 가서 각 각각 여러분 각종 각자 제각기 하도록하다 와 과 그러므로 그래서 고로 한 까닭에 하기 때문에 거니와 이지만 대하여 관하여 관한 과연 실로 아니나다를가 생각한대로 진짜로 한적이있다 하곤하였다 하 하하 허허 아하 거바 와 오 왜 어째서 무엇때문에 어찌 하겠는가 무슨 어디 어느곳 더군다나 하물며 더욱이는 어느때 언제 야 이봐 어이 여보시오 흐흐 흥 휴 헉헉 헐떡헐떡 영차 여차 어기여차 끙끙 아야 앗 아야 콸콸 졸졸 좍좍 뚝뚝 주룩주룩 솨 우르르 그래도 또 그리고 바꾸어말하면 바꾸어말하자면 혹은 혹시 답다 및 그에 따르는 때가 되어 즉 지든지 설령 가령 하더라도 할지라도 일지라도 지든지 몇 거의 하마터면 인젠 이젠 된바에야 된이상 만큼	어찌됏든 그위에 게다가 점에서 보아 비추어 보아 고려하면 하게될것이다 일것이다 비교적 좀 보다더 비하면 시키다 하게하다 할만하다 의해서 연이서 이어서 잇따라 뒤따라 뒤이어 결국 의지하여 기대여 통하여 자마자 더욱더 불구하고 얼마든지 마음대로 주저하지 않고 곧 즉시 바로 당장 하자마자 밖에 안된다 하면된다 그래 그렇지 요컨대 다시 말하자면 바꿔 말하면 즉 구체적으로 말하자면 시작하여 시초에 이상 허 헉 허걱 바와같이 해도좋다 해도된다 게다가 더구나 하물며 와르르 팍 퍽 펄렁 동안 이래 하고있었다 이었다 에서 로부터 까지 예하면 했어요 해요 함께 같이 더불어 마저 마저도 양자 모두 습니다 가까스로 하려고하다 즈음하여 다른 다른 방면으로 해봐요 습니까 했어요 말할것도 없고 무릎쓰고 개의치않고 하는것만 못하다 하는것이 낫다 매 매번 들 모 어느것 어느 로써 갖고말하자면 어디 어느쪽 어느것 어느해 어느 년도 라 해도 언젠가 어떤것 어느것 저기 저쪽 저것 그때 그럼 그러면 요만한걸 그래 그때 저것만큼 그저 이르기까지 할 줄 안다 할 힘이 있다 너 너희 당신 어찌 설마 차라리 할지언정 할지라도 할망정 할지언정 구토하다 게우다 토하다 메쓰겁다 옆사람 퉤 쳇 의거하여 근거하여 의해 따라 힘입어 그 다음 버금 두번째로 기타 첫번째로 나머지는 그중에서 견지에서 형식으로 쓰여 입장에서 위해서 단지 의해되다 하도록시키다 뿐만아니라 반대로 전후 전자 앞의것 잠시 잠깐 하면서 그렇지만 다음에 그러한즉 그런즉 남들 아무거나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 어떻게 만약 만일 위에서 서술한바와같이 인 듯하다 하지 않는다면 만약에 무엇 무슨 어느 어떤 아래윗 조차 한데 그럼에도 불구하고 여전히 심지어 까지도 조차도 하지 않도록 않기 위하여 때 시각 무렵 시간 동안 어때 어떠한 하여금 네 예 우선 누구 누가 알겠는가 아무도 줄은모른다 줄은 몰랏다 하는 김에 겸사겸사 하는바 그런 까닭에 한 이유는 그러니 그러니까 때문에 그 너희 그들 너희들 타인 것 것들 너 위하여 공동으로 동시에 하기 위하여 어찌하여 무엇때문에 붕붕 윙윙 나 우리 엉엉 휘익 윙윙 오호 아하 어쨋든 만 못하다	하기보다는 차라리 하는 편이 낫다 흐흐 놀라다 상대적으로 말하자면 마치 아니라면 쉿 그렇지 않으면 그렇지 않다면 안 그러면 아니었다면 하든지 아니면 이라면 좋아 알았어 하는것도 그만이다 어쩔수 없다 하나 일 일반적으로 일단 한켠으로는 오자마자 이렇게되면 이와같다면 전부 한마디 한항목 근거로 하기에 아울러 하지 않도록 않기 위해서 이르기까지 이 되다 로 인하여 까닭으로 이유만으로 이로 인하여 그래서 이 때문에 그러므로 그런 까닭에 알 수 있다 결론을 낼 수 있다 으로 인하여 있다 어떤것 관계가 있다 관련이 있다 연관되다 어떤것들 에 대해 이리하여 그리하여 여부 하기보다는 하느니 하면 할수록 운운 이러이러하다 하구나 하도다 다시말하면 다음으로 에 있다 에 달려 있다 우리 우리들 오히려 하기는한데 어떻게 어떻해 어찌됏어 어때 어째서 본대로 자 이 이쪽 여기 이것 이번 이렇게말하자면 이런 이러한 이와 같은 요만큼 요만한 것 얼마 안 되는 것 이만큼 이 정도의 이렇게 많은 것 이와 같다 이때 이렇구나 것과 같이 끼익 삐걱 따위 와 같은 사람들 부류의 사람들 왜냐하면 중의하나 오직 오로지 에 한하다 하기만 하면 도착하다 까지 미치다 도달하다 정도에 이르다 할 지경이다 결과에 이르다 관해서는 여러분 하고 있다 한 후 혼자 자기 자기집 자신 우에 종합한것과같이 총적으로 보면 총적으로 말하면 총적으로 대로 하다 으로서 참 그만이다 할 따름이다 쿵 탕탕 쾅쾅 둥둥 봐 봐라 아이야 아니 와아 응 아이 참나 년 월 일 령 영 일 이 삼 사 오 육 륙 칠 팔 구 이천육 이천칠 이천팔 이천구 하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 령 영 ".split())

In [ ]:
import re
from sklearn.metrics.pairwise import cosine_similarity
from konlpy.tag import Okt

okt = Okt()

def sentiment_predict(new_sentence):
    # 간단 전처리
    new_sentence = re.sub(r'[^ㄱ-ㅎㅏ-ㅣ가-힣]','', new_sentence)
    new_sentence = okt.morphs(new_sentence)
    new_sentence = [word for word in new_sentence if not word in ko_stopwords]
    new_sentence = " ".join(new_sentence)
    
    # 벡터화
    input_vec = tfidf_vectorizer.transform([new_sentence])
    
    # 코사인 유사도 계산
    sim = cosine_similarity(input_vec, text_vecs).flatten()
    sim_idx = sim.argsort()[::-1][:6]       # 유사 문장 상위 5개
    sim_docs = text_df.iloc[sim_idx]
    
    # 긍/부정 판단
    pos_count = (sim_docs['label'] == 1).sum()
    neg_count = (sim_docs['label'] == 0).sum()
    
    if pos_count > neg_count:
        sentiment = 'positive'
    else:
        sentiment = 'negative'
        
    return sentiment

In [34]:
sentiment_predict('꿀잼')

'positive'